Write-Host "Start backend in this window:"
Write-Host "  cd $PSScriptRoot\backend"
Write-Host "  npm install"
Write-Host "  npm start"
Write-Host ""
Write-Host "Then open another PowerShell and run:"
Write-Host "  cd $PSScriptRoot"
Write-Host "  python -m http.server 8080 --directory web"
Write-Host ""
Write-Host "Web: http://localhost:8080"
Write-Host "API: http://localhost:5000/health"
