name: hasani_customer_app
description: Hasani ARMS customer portal.
publish_to: "none"
version: 3.0.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
